### ISSUE TITLE
Initial Stacks event listener

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-hyperchains#1]

**Comment by gregorycoppola** [comment]
What is this actually going to listen *to*?

**Comment by kantai** [comment]
It will listen to a `stacks-node` instance. I think in the initial version, we should just assume that it is registered as an observer on a `stacks-node` that is syncing from genesis (i.e., it doesn't need to do things like request data over the API).

This listener should be registered as an observer for `new_block` requests from the `stacks-node`, and basically implement the structs in place in the MockController:

https://github.com/hirosystems/stacks-hyperchains/blob/master/testnet/stacks-node/src/burnchains/mock_events.rs

The goal is that the listener, when the `new_block` endpoint is invoked, would feed the information required into an Indexer, which the `src/burnchains` module already knows how to use to store and process the information in the sortition DB.

**Comment by saralab** [comment]
- Integration test - Spin up the regtest stacks-node to emit events to hyperchain node

**Comment by kantai** [comment]
Update: we should use `warp` for this webserver. In the most simple case, an implementation of this would look like the event listener that the integration tests use. That's here:

https://github.com/stacks-network/stacks-blockchain/blob/master/testnet/stacks-node/src/tests/neon_integrations.rs#L119
