### ISSUE TITLE
Anchor block proposal RPC interface

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-hyperchains#11]
Hyperchain nodes that are participating as miners will need to expose a new RPC interface for receiving block proposals. This interface will accept the proposed block data as well as a signature over that data. The signature must be verified as coming from one of the other miners (as a first implementation, the miner set can be included in the node configuration toml, but eventually, we should be able to read it out of the configured hyperchains contract).

The recipient will verify that the block:

1. Builds off of the current chain tip
2. Includes any confirmed deposit events between the last chain tip and the new chain tip
3. Confirms the most recently signed microblock

Once the recipient verifies the above, they return an HTTP OK response with the signature. The exact mechanics of that signature will depend on the implementation of the multi-party anchor block signature scheme.

**Comment by gregorycoppola** [comment]
Do we have to do BFT?

Can't we just keep closer to the current system?

That would be:
1) less work to make the trusted subnets from the current code
2) less work to backport trusted subnets to something more like "app chains"

**Comment by kantai** [comment]
Stacks mainnet operates under different assumptions than subnets, notably open membership. For a closed membership system, there's a proven body of literature / protocols that are correct and efficient: we should use those. PoX and app chains also have other requirements (like leader election driven by BTC blocks) that subnets shouldn't be limited by.

There are multiple off-the-shelf implementations of BFT that could be used. The BFT component also should be relatively independent of most of the other changes required for subnets.

Regarding "backporting" to app chains, I'm not sure backporting this consensus process to app chains is a goal --- there's almost no overlap between the actual consensus rules of subnets and app chains (indeed, that's the biggest difference between the two). Other work (as mentioned above) is independent of the BFT component. Therefore, to the extent that other work is useful to either app chains or the stacks-blockchain node, it should be easy to backport.

**Comment by gregorycoppola** [comment]
Which paper are we implementing?

**Comment by kantai** [comment]
The goal is to use a library. I believe most library implementations use a RAFT-based protocol.

**Comment by saralab** [comment]
Merged, closing
