### ISSUE TITLE
Making the network id a required configuration setting

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-hyperchains#112]
Hyperchains need to differentiate from one another using their network ID -- this also prevents transactions from the hyperchain being replayed on other networks (which would be bad).

In order to do this, we have to make the network identifier and chain identifiers configurable.

Currently, the code just switches between:

```rust
pub const CHAIN_ID_MAINNET: u32 = 0x00000001;
pub const CHAIN_ID_TESTNET: u32 = 0x80000000;
```

and

```rust
pub const NETWORK_ID_MAINNET: u32 = 0x17000000;
pub const NETWORK_ID_TESTNET: u32 = 0xff000000;
```

However, everywhere these get used needs to be replaced with configurable settings.

This change should be tested by configuring random values for these in the `l1_integration` and `neon_integration` tests.

**Comment by gregorycoppola** [comment]
What are the values going to be for `chain_id` and `network_id`?

I.e., what are the current values and what are some possible values?

**Comment by kantai** [comment]
The current values are those constants -- the possible values should be any u32 values

**Comment by gregorycoppola** [comment]
1) I think it's confusing that the values for both `chain` and `network` are both `MAINNET` and `TESTNET`. 
It seems like the values should be distinct for the distinction between the two variables to be clear.

2) What about values like `stacks_layer_1`, `mockstack` and `bitcoin`? These are in the code but don't have a place in the scheme right now.
