### ISSUE TITLE
Implement NFT case study for hyperchains prototype

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-hyperchains#17]
We should implement a case study application and document how the application can be spun up in two ways:

1. On the actual Stacks testnet
2. On a local Stacks mocknet

This will require a few different pieces:

- [ ] A simple Stacks NFT contract, which exposes an interface that the sample hyperchains contract can invoke
- [ ] A counterpart to the Stacks NFT contract for launching on the hyperchain, which exposes the requisite `depost` and `withdraw` interfaces.
- [ ] An integration test which:
       - Starts a Stacks mocknet node
       - Deploys the sample hyperchain contract to the Stacks node
       - Deploys the Stacks NFT contract
       - Deploys the Hyperchain NFT contract
       - Tests: mint on hyperchain, withdraw to Stacks chain
       - Tests: mint on Stacks chain, deposit to hyperchain

**Comment by lgalabru** [comment]
A lighter version of http://wyvernprotocol.com could be interesting.

**Comment by saralab** [comment]
Include Transfers of NFTs within Hyperchains in the use case

**Comment by saralab** [comment]
Merged, closing this
