### ISSUE TITLE
Integrate deposits into Hyperchain block assembly + processing

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-hyperchains#37]
Similar to the processing of `StxTransferOp`s in the L1 `stacks-blockchain`, the `hyperchain-node`'s block assembly and processing code will need to shuttle the `Deposit` events from the `burnchain` module (produced as part of #13) into the hyperchain's state.

To do this, we would want to define an interface for hyperchain contracts like:

```clar
(define-public (hyperchain-deposit-<ft-name> amount recipient))
```

That contracts must supply.  This would be invoked during block processing to actually execute the deposit.

**Comment by saralab** [comment]
Done and Dusted
