### ISSUE TITLE
New multiple-signer block format

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-hyperchains#4]

**Comment by gregorycoppola** [comment]
What does this involve?

**Comment by kantai** [comment]
This would boil down to adding a new field to `struct StacksBlockHeader` for holding a signature (or rather, a Vec of signatures), updating the microblock header to use the Vec of signatures, rather than the single signature "MessageSignature" type, and then updating serialization and deserialization code for those changes.

I would base your branch on `feat/initial-burnchains-replacement`
