### ISSUE TITLE
Add withdraw methods for NFTs, FTs, and STX

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-hyperchains#59]
L2 assets, in order to be valid for withdrawal, must be _destroyed_ in L2 before they can be recovered to L1.

This will require three new Clarity functions:

```
stx-withdraw
ft-withdraw
nft-withdraw
```

These will be logically pretty similar to _burn_ methods, with the difference being that the hyperchain miners will monitor these withdraw operations for processing withdraws (in the first version, the miner will simply issue the withdraw on L1 after the events are confirmed).

**Comment by pavitthrap** [comment]
Possible issue breakdown:
(1) Implement clarity functions
(2) Track + store withdraw events (in DB?) 
(3) Implement withdraw function in hyperchains contract + store in sortDB
(4) Read withdraw ops & process them in hyperchain (this would also utilize info stored in (2))

**Comment by kantai** [comment]
Implemented via #71
