### ISSUE TITLE
Preventing microblock loss

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-hyperchains#67]
This is related to "disabling L2 forks" (#66), but it applies to microblocks, and it requires slightly more complex mining behavior. The basic idea is that the `hyperchain-node` should *never* issue an anchor block that does not incorporate all of the microblocks produced following the previous anchor block. This should be possible because the miner is also always responsible for producing microblocks. The miner should therefore always know which microblocks were produced.

Practically, this means a couple changes need to occur in the `neon_node` and its interaction with the `miner` module:

1. The `build_anchor_block` method should *always* use the microblocks produced by the miner.
2. Once the miner broadcasts their anchor block (i.e., sends the L1 transaction), they *must* stop producing microblocks until that anchor block is confirmed.

**Comment by gregorycoppola** [comment]
We are adding to this, the ability to:

* spend the first "M minutes" on micro-blocks, before starting the anchored block

**Comment by kantai** [comment]
Implemented and tested via #102 and #111
