### ISSUE TITLE
feat: Testing constructs to allow strong, determinstic asserts in Mock environment

### ISSUE THREAD

**Issue by gregorycoppola** [hirosystems/stacks-hyperchains#87]
**Is your feature request related to a problem? Please describe.**
As far as I know, when writing an integration test, it is not possible to deterministically assert quantities based on the number of "Stacks" blocks (or L2 blocks in the hyper-chain) that have been mined.

For example, let us say we want to assert **the number of stacks blocks that have been mined**, at a certain execution point.

This is something I wanted to do in making a "Forking integration test" for #66. I wanted the forking test to be able to assert the number of Stacks blocks mined. Here is a snippet:

```
    let common_ancestor = btc_regtest_controller.next_block(None);
    wait_for_block(&blocks_processed);

    // Note: Burn height gets to 3 before "stacks" height gets to 1 in this test framework.
    assert_eq!(1, get_stacks_tip_height(&sortition_db));
    assert_eq!(3, get_burn_tip_height(&sortition_db));

    {
        let mut cursor = common_ancestor; // btc_regtest_controller.next_block(Some(common_ancestor));
        for i in 0..4 {
            cursor = btc_regtest_controller.next_block(Some(cursor));
            wait_for_block(&blocks_processed);
        }
        btc_regtest_controller.next_block(Some(cursor));
    }
    thread::sleep(Duration::from_millis(1000));

    assert_eq!(6, get_stacks_tip_height(&sortition_db));   // Not determinstically assertable!
```

This test can either pass or fail, depending on non-determinstic factors.

**Describe the solution you'd like**
I'd like some combination of function calls that I can make that would let me assert that a certain number of stacks blocks have passed.

This way, we can write tests that both:

1) make strong assertions about execution state
2) pass deterministically

Right now, our tests often:

1) don't make strong assertions, because we are worried they will flake
2) end up flaking anyway

This means that either:

1) you can break behavior without breaking a test
2) we don't know whether to believe test failures

**Comment by saralab** [comment]
Merged, closing
