### ISSUE TITLE
Off by 1 behavior in tests

### ISSUE THREAD

**Issue by gregorycoppola** [hirosystems/stacks-hyperchains#90]
**Describe the bug**
Right now, in order to not hang, we have to write our tests with an extra call to `MockController::next_block` relative to what one would expect. E.g., currently, in `mockstack_integration_test`, where the system is set to wake up on burn block 1, we have:

```
    wait_for_runloop(&blocks_processed);
    btc_regtest_controller.next_block();   // burn block 0
    btc_regtest_controller.next_block();  // burn block 1
    next_block_and_wait(&mut btc_regtest_controller, &blocks_processed); // creates burn block 2
```

Removing one call to `btc_regtest_controller.next_block()` will cause this test to hang forever and fail. However, this means we cannot actually get a stacks block for the requested first burn block, which is 1.

**Environment (please complete the following information):**
all

**Additional context**
We could adjust all of the tests to simply add an extra burn block. But, this behavior probably suggests that info from the requested first burn block is actually going to be missed.

#89 includes logs that help explain why this "extra block" is necessary.

**Comment by gregorycoppola** [comment]
This probably isn't actionable against the current code base.

**Comment by psq** [comment]
This not actionable till someone gives access to lower level
